# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp (iOS)
  pod 'SwiftLint'
end

target 'DemoApp (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp (macOS)
  pod 'SwiftLint'
end
